name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build . --file Dockerfile.dev --tag ${{ secrets.DOCKERHUB_USERNAME }}/docker_images:frontend
        docker-compose up
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker_images:frontend
