name: Onboarding vm

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Execute file
      run: |
        ls
        pwd
        sh ./start.sh aug t3.micro
        
