name: Onboarding vm

on:
  push:
    branches: [ onboarding ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Execute py file
      run: |
        ls
